import { ArrowLeft, CalendarPlus, Check, ChevronRight, CirclePlus, ListTree, Target, Trash2 } from "lucide-react";
import { Button } from "../components/ui/Button";
import { EmptyState } from "../components/ui/EmptyState";
import { Progress } from "../components/ui/Progress";
import { StatusPill } from "../components/ui/StatusPill";
import type { CSSProperties } from "react";
import type { GoalDetailPageProps, GoalsPageProps } from "./types";

export function GoalsPage({ goals, goalProgress = {}, onAddGoal, onOpenGoal }: GoalsPageProps) {
  return <main className="page goals-page"><div className="page-heading"><div><p className="eyebrow">目标库</p><h1>把方向拆成走得下去的路径。</h1></div><Button tone="primary" onClick={onAddGoal}><CirclePlus size={17} /> 新建目标</Button></div><div className="goal-library">{goals.length ? goals.map((goal) => {const progress = goalProgress[goal.id]; return <article className="surface goal-library-card" key={goal.id}><div className="goal-library-card__meta"><StatusPill status={goal.status === "completed" ? "completed" : "active"} /><span>{goal.dueDate ? `截止 ${goal.dueDate}` : "无明确截止日期"}</span></div><h2>{goal.title}</h2><p>{goal.description || "还没有描述"}</p><Progress value={progress?.value ?? 0} tone="cyan" /><footer><span>{progress?.label ?? "尚未开始"}</span><Button size="sm" tone="quiet" onClick={() => onOpenGoal?.(goal.id)}>查看详情 <ChevronRight size={15} /></Button></footer></article>}) : <EmptyState title="目标库是空的" description="先记录一个近期想推进的方向，不必立刻把它规划完整。" action={<Button tone="primary" onClick={onAddGoal}>新建第一个目标</Button>} />}</div></main>;
}

function treeRows(steps: GoalDetailPageProps["steps"]) { const byParent = new Map<string | undefined, typeof steps>(); steps.forEach((step) => { const group = byParent.get(step.parentStepId) ?? []; group.push(step); byParent.set(step.parentStepId, group); }); const rows: Array<{ step: typeof steps[number]; depth: number }> = []; const walk = (parentId: string | undefined, depth: number) => (byParent.get(parentId) ?? []).sort((a,b) => a.order-b.order).forEach((step) => { rows.push({ step, depth }); walk(step.id, depth + 1); }); walk(undefined, 0); return rows; }
export function GoalDetailPage({ goal, steps, planBlocks, completionLogs, progress, onBack, onDeleteGoal, onAddStep, onEditStep, onToggleStep, onAddPlan }: GoalDetailPageProps) {
  const rows = treeRows(steps); const planned = planBlocks.filter((item) => item.status === "planned").length; const totalMinutes = completionLogs.reduce((sum, log) => sum + (log.actualMinutes ?? 0), 0);
  return <main className="page goal-detail"><button className="back-link" onClick={onBack}><ArrowLeft size={16} /> 返回目标库</button><section className="goal-hero"><div><p className="eyebrow">{goal.dueDate ? `截止 ${goal.dueDate}` : "持续目标"}</p><h1>{goal.title}</h1><p>{goal.description || "为这个目标添加一个说明，帮助未来的自己重新进入状态。"}</p></div><div className="goal-hero__actions"><Button tone="danger" onClick={onDeleteGoal}><Trash2 size={16} /> 删除目标</Button><Button onClick={() => onAddPlan?.({ goalId: goal.id })}><CalendarPlus size={16} /> 安排一次推进</Button><Button tone="primary" onClick={() => onAddStep?.()}><CirclePlus size={16} /> 添加步骤</Button></div></section>
    <div className="goal-stats"><div className="surface"><Target size={18}/><strong>{progress?.value ?? 0}%</strong><span>{progress?.label ?? "目标进展"}</span></div><div className="surface"><ListTree size={18}/><strong>{steps.filter((step) => step.isCompleted).length}/{steps.length}</strong><span>已完成步骤</span></div><div className="surface"><Check size={18}/><strong>{Math.round(totalMinutes / 6) / 10} h</strong><span>{planned ? `还有 ${planned} 项已安排` : "累计真实投入"}</span></div></div>
    <section className="surface steps-card"><div className="section-heading"><div><p className="eyebrow">步骤地图</p><h2>下一次推进什么</h2></div><Button size="sm" onClick={() => onAddStep?.()}>添加一级步骤</Button></div>{rows.length ? <div className="step-tree">{rows.map(({step, depth}) => <article className={`step-row ${step.isCompleted ? "is-completed" : ""}`} style={{ "--step-depth": depth } as CSSProperties} key={step.id}><button className="check-control" onClick={() => onToggleStep?.(step)} aria-label={`${step.isCompleted ? "取消完成" : "完成"}${step.title}`}>{step.isCompleted && <Check size={14}/>}</button><div><strong>{step.title}</strong>{step.notes && <p>{step.notes}</p>}</div><div className="step-row__actions"><Button tone="quiet" size="sm" onClick={() => onAddPlan?.({ goalId: goal.id, goalStepId: step.id, title: step.title })}>安排</Button><Button tone="quiet" size="sm" onClick={() => onEditStep?.(step)}>编辑</Button><button className="ui-icon-button" aria-label={`添加 ${step.title} 的子步骤`} onClick={() => onAddStep?.(step.id)}><CirclePlus size={17}/></button></div></article>)}</div> : <EmptyState title="从一个可执行步骤开始" description="例如“模拟题训练”或“整理项目案例”，之后可以再拆得更细。" action={<Button onClick={() => onAddStep?.()}>添加步骤</Button>} />}</section>
  </main>;
}
