import { ArrowRight, CalendarDays, CheckCircle2, Clock3, FileText } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "../components/ui/Button";
import { EmptyState } from "../components/ui/EmptyState";
import type { ReviewPageProps } from "./types";

export function ReviewPage({ summary, planBlocks, onChangeDate, onSaveReview, onReschedule }: ReviewPageProps) {
  const [reflection, setReflection] = useState(summary.review?.reflection ?? ""); const [blockers, setBlockers] = useState(summary.review?.blockers ?? ""); const [tomorrowFocus, setTomorrowFocus] = useState(summary.review?.tomorrowFocus ?? "");
  useEffect(() => {setReflection(summary.review?.reflection ?? ""); setBlockers(summary.review?.blockers ?? ""); setTomorrowFocus(summary.review?.tomorrowFocus ?? "");}, [summary.date, summary.review]);
  const remaining = planBlocks.filter((plan) => plan.status === "planned");
  return <main className="page review-page"><div className="page-heading"><div><p className="eyebrow">每日回顾</p><h1>看清今天实际推进了什么。</h1></div><label className="date-picker"><CalendarDays size={16}/><input type="date" value={summary.date} onChange={(event) => onChangeDate?.(event.target.value as typeof summary.date)} /></label></div>
    <section className="review-metrics"><div className="surface"><CheckCircle2 size={19}/><strong>{summary.completedCount}<small> / {summary.plannedCount}</small></strong><span>完成安排</span></div><div className="surface"><Clock3 size={19}/><strong>{Math.round(summary.actualMinutes / 6) / 10}<small> h</small></strong><span>真实投入</span></div><div className="surface"><FileText size={19}/><strong>{summary.completionLogs.length}</strong><span>留下完成记录</span></div></section>
    <div className="review-grid"><section className="surface completion-records"><div className="section-heading"><div><p className="eyebrow">自动汇总</p><h2>今天留下的成果</h2></div></div>{summary.completionLogs.length ? summary.completionLogs.map((log) => <article key={log.id}><span className="record-mark"><CheckCircle2 size={16}/></span><div><strong>{log.outcome || "已完成一项安排"}</strong>{log.notes && <p>{log.notes}</p>}{log.nextStep && <small>下一步：{log.nextStep}</small>}</div>{log.actualMinutes && <span>{log.actualMinutes} min</span>}</article>) : <EmptyState title="完成记录会自动出现在这里" description="完成安排时写下成果或备注，就能在回顾里看到。" />}</section>
      <section className="surface review-form"><div className="section-heading"><div><p className="eyebrow">你的判断</p><h2>写给明天的自己</h2></div></div><label>今天有什么收获？<textarea value={reflection} onChange={(e) => setReflection(e.target.value)} placeholder="例如：模拟题的字符串解析速度变快了。" /></label><label>哪里卡住了，或计划为什么变了？<textarea value={blockers} onChange={(e) => setBlockers(e.target.value)} placeholder="不写也没关系。" /></label><label>明天最值得继续的一件事<textarea value={tomorrowFocus} onChange={(e) => setTomorrowFocus(e.target.value)} placeholder="只写一件，让明天容易开始。" /></label><Button tone="primary" onClick={() => onSaveReview?.({reflection, blockers, tomorrowFocus})}>保存今日回顾</Button></section></div>
    <section className="surface remaining-card"><div className="section-heading"><div><p className="eyebrow">未完成安排</p><h2>{remaining.length ? "为它们决定去向" : "今天的安排已处理完"}</h2></div></div>{remaining.map((plan) => <article key={plan.id}><strong>{plan.title}</strong><div><Button size="sm" tone="quiet" onClick={() => onReschedule?.(plan, "backlog")}>退回待安排</Button><Button size="sm" onClick={() => onReschedule?.(plan, "tomorrow")}>移到明天 <ArrowRight size={14}/></Button></div></article>)}</section>
  </main>;
}
